# yaml-language-server: $schema=../../recipe.schema.json

gid: f6c7af65-86e0-48c3-80da-08c4605f575c
title: B2B Commerce
summary: Add Business-to-Business (B2B) functionality with company locations,
  quantity rules, and volume pricing
description: |
  This recipe adds comprehensive B2B functionality to your Hydrogen storefront, enabling business customers to:

  - Select their company location for contextualized pricing
  - View and respect quantity rules (minimum, maximum, increment)
  - See volume-based price breaks for bulk purchases
  - Access B2B-specific pricing through contextualized GraphQL queries

  The implementation includes a location selector modal, quantity rule displays on product pages, 
  and cart functionality that respects B2B quantity rules. All product queries are contextualized 
  with buyer information (company location + customer token) to ensure accurate B2B pricing.
notes:
  - For production, all product queries should be contextualized with buyer
    information
requirements: |
  - Shopify Plus plan with B2B enabled
  - New customer accounts activated
  - At least one B2B company with customer access configured
  - Products with quantity rules or volume pricing configured (optional but recommended for testing)
ingredients:
  - path: templates/skeleton/app/components/B2BLocationProvider.tsx
    description: React context provider that manages company location state across
      the application
  - path: templates/skeleton/app/components/B2BLocationSelector.tsx
    description: Modal component that allows customers to choose which company
      location to use for pricing
  - path: templates/skeleton/app/components/PriceBreaks.tsx
    description: Component that displays volume pricing tiers showing bulk purchase
      discounts
  - path: templates/skeleton/app/components/QuantityRules.tsx
    description: Component that displays minimum, maximum, and increment quantity
      requirements for B2B products
  - path: templates/skeleton/app/graphql/customer-account/CustomerLocationsQuery.ts
    description: GraphQL query to fetch company locations from the Customer Account
      API for B2B customers
  - path: templates/skeleton/app/routes/b2blocations.tsx
    description: Route handler for location selection that automatically sets
      location if customer has only one
deletedFiles: []
steps:
  - type: PATCH
    step: "1"
    name: Document B2B features, requirements, and implementation details in the
      project README
    description: Update the README file with comprehensive B2B commerce
      documentation, explaining features like company locations, quantity rules,
      and volume pricing implementation
    diffs:
      - file: README.md
        patchFile: README.md.db10ed.patch
  - type: NEW_FILE
    step: "2"
    name: Create a React context provider to manage company location state across
      the app
    description: Create a React context provider that manages the selected company
      location state and provides location switching functionality throughout
      the B2B application
    ingredients:
      - path: templates/skeleton/app/components/B2BLocationProvider.tsx
  - type: PATCH
    step: "3"
    name: Update quantity controls to respect B2B minimum, maximum, and increment
      rules
    description: Update cart line item quantity controls to honor B2B quantity rules
      including minimum order quantities, maximum limits, and increment
      requirements
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.2c9a50.patch
  - type: NEW_FILE
    step: "4"
    name: Build a modal that lets customers choose which company location to use for
      pricing
    description: Create a modal component that displays available company locations
      and allows B2B customers to select the appropriate location for
      contextualized pricing
    ingredients:
      - path: templates/skeleton/app/components/B2BLocationSelector.tsx
  - type: PATCH
    step: "5"
    name: Add a location selector button to the header for switching between company
      locations
    description: Add a location selector button to the site header that allows B2B
      customers to easily switch between their company's different locations
    diffs:
      - file: app/components/Header.tsx
        patchFile: Header.tsx.e25645.patch
  - type: NEW_FILE
    step: "6"
    name: Display volume pricing tiers that show bulk purchase discounts
    description: Create a component that displays volume pricing breaks, showing
      customers the discounted prices they'll receive for bulk purchases at
      different quantity thresholds
    ingredients:
      - path: templates/skeleton/app/components/PriceBreaks.tsx
  - type: PATCH
    step: "7"
    name: Accept quantity parameter to support B2B minimum quantity and increment
      rules
    description: Update the ProductForm component to accept and handle quantity
      parameters that enforce B2B minimum quantities and increment rules when
      adding products to cart
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.649d3b.patch
  - type: NEW_FILE
    step: "8"
    name: Show minimum, maximum, and increment quantity requirements for B2B products
    description: Create a component that displays B2B quantity rules to customers,
      showing minimum order quantities, maximum limits, and required increments
      for business products
    ingredients:
      - path: templates/skeleton/app/components/QuantityRules.tsx
  - type: PATCH
    step: "9"
    name: Add quantity rules and price breaks to cart GraphQL fragments
    description: Update GraphQL fragments to include quantity rules and price break
      data needed for B2B functionality in cart queries
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.026109.patch
  - type: NEW_FILE
    step: "10"
    name: Query company locations from the Customer Account API for B2B customers
    description: Create a GraphQL query that fetches all available company locations
      for B2B customers from the Customer Account API
    ingredients:
      - path: templates/skeleton/app/graphql/customer-account/CustomerLocationsQuery.ts
  - type: PATCH
    step: "11"
    name: Wrap the app with B2B location provider and add company location types
    description: Wrap the application with the B2B location provider context and add
      TypeScript type definitions for company location data
    diffs:
      - file: app/root.tsx
        patchFile: root.tsx.5e9998.patch
  - type: NEW_FILE
    step: "12"
    name: Handle location selection and automatically set location if customer has
      only one
    description: Create a route handler that processes location selection requests
      and automatically sets the location if a B2B customer only has access to
      one company location
    ingredients:
      - path: templates/skeleton/app/routes/b2blocations.tsx
  - type: PATCH
    step: "13"
    name: Clear company location and customer data from cart when logging out
    description: Update the logout process to clear B2B-specific data including
      selected company location and customer context from the cart session
    diffs:
      - file: app/routes/account_.logout.tsx
        patchFile: account_.logout.tsx.a1f12e.patch
  - type: PATCH
    step: "14"
    name: Contextualize product queries with buyer information and display B2B
      pricing details
    description: Update product queries to include buyer context (company location
      and customer token) and display B2B-specific pricing, quantity rules, and
      volume discounts on product pages
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.6f2e82.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 0511444a026f5b80c3927fbc2e31b1ab827cfeae
