/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./root";
import { Route as routesSitemapRouteImport } from "./routes/sitemap";
import { Route as routesSearchRouteImport } from "./routes/search";
import { Route as routesRobotsRouteImport } from "./routes/robots";
import { Route as routesCollectionsRouteImport } from "./routes/collections";
import { Route as routesCartRouteImport } from "./routes/cart";
import { Route as routesAccountRouteImport } from "./routes/account";
import { Route as routesCatchallRouteImport } from "./routes/catchall";
import { Route as routesHomeRouteImport } from "./routes/home";
import { Route as routesProductRouteImport } from "./routes/product";
import { Route as routesCollectionRouteImport } from "./routes/collection";

const routesSitemapRoute = routesSitemapRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any);
const routesSearchRoute = routesSearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const routesRobotsRoute = routesRobotsRouteImport.update({
  id: "/robots.txt",
  path: "/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const routesCollectionsRoute = routesCollectionsRouteImport.update({
  id: "/collections",
  path: "/collections",
  getParentRoute: () => rootRouteImport,
} as any);
const routesCartRoute = routesCartRouteImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRouteImport,
} as any);
const routesAccountRoute = routesAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => rootRouteImport,
} as any);
const routesCatchallRoute = routesCatchallRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const routesHomeRoute = routesHomeRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const routesProductRoute = routesProductRouteImport.update({
  id: "/products/$handle",
  path: "/products/$handle",
  getParentRoute: () => rootRouteImport,
} as any);
const routesCollectionRoute = routesCollectionRouteImport.update({
  id: "/collections/$handle",
  path: "/collections/$handle",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof routesHomeRoute;
  "/$": typeof routesCatchallRoute;
  "/account": typeof routesAccountRoute;
  "/cart": typeof routesCartRoute;
  "/collections": typeof routesCollectionsRoute;
  "/robots.txt": typeof routesRobotsRoute;
  "/search": typeof routesSearchRoute;
  "/sitemap.xml": typeof routesSitemapRoute;
  "/collections/$handle": typeof routesCollectionRoute;
  "/products/$handle": typeof routesProductRoute;
}
export interface FileRoutesByTo {
  "/": typeof routesHomeRoute;
  "/$": typeof routesCatchallRoute;
  "/account": typeof routesAccountRoute;
  "/cart": typeof routesCartRoute;
  "/collections": typeof routesCollectionsRoute;
  "/robots.txt": typeof routesRobotsRoute;
  "/search": typeof routesSearchRoute;
  "/sitemap.xml": typeof routesSitemapRoute;
  "/collections/$handle": typeof routesCollectionRoute;
  "/products/$handle": typeof routesProductRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof routesHomeRoute;
  "/$": typeof routesCatchallRoute;
  "/account": typeof routesAccountRoute;
  "/cart": typeof routesCartRoute;
  "/collections": typeof routesCollectionsRoute;
  "/robots.txt": typeof routesRobotsRoute;
  "/search": typeof routesSearchRoute;
  "/sitemap.xml": typeof routesSitemapRoute;
  "/collections/$handle": typeof routesCollectionRoute;
  "/products/$handle": typeof routesProductRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/account"
    | "/cart"
    | "/collections"
    | "/robots.txt"
    | "/search"
    | "/sitemap.xml"
    | "/collections/$handle"
    | "/products/$handle";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/account"
    | "/cart"
    | "/collections"
    | "/robots.txt"
    | "/search"
    | "/sitemap.xml"
    | "/collections/$handle"
    | "/products/$handle";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/account"
    | "/cart"
    | "/collections"
    | "/robots.txt"
    | "/search"
    | "/sitemap.xml"
    | "/collections/$handle"
    | "/products/$handle";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  routesHomeRoute: typeof routesHomeRoute;
  routesCatchallRoute: typeof routesCatchallRoute;
  routesAccountRoute: typeof routesAccountRoute;
  routesCartRoute: typeof routesCartRoute;
  routesCollectionsRoute: typeof routesCollectionsRoute;
  routesRobotsRoute: typeof routesRobotsRoute;
  routesSearchRoute: typeof routesSearchRoute;
  routesSitemapRoute: typeof routesSitemapRoute;
  routesCollectionRoute: typeof routesCollectionRoute;
  routesProductRoute: typeof routesProductRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sitemap.xml": {
      id: "/sitemap.xml";
      path: "/sitemap.xml";
      fullPath: "/sitemap.xml";
      preLoaderRoute: typeof routesSitemapRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof routesSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/robots.txt": {
      id: "/robots.txt";
      path: "/robots.txt";
      fullPath: "/robots.txt";
      preLoaderRoute: typeof routesRobotsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collections": {
      id: "/collections";
      path: "/collections";
      fullPath: "/collections";
      preLoaderRoute: typeof routesCollectionsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cart": {
      id: "/cart";
      path: "/cart";
      fullPath: "/cart";
      preLoaderRoute: typeof routesCartRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/account": {
      id: "/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof routesAccountRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof routesCatchallRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof routesHomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/$handle": {
      id: "/products/$handle";
      path: "/products/$handle";
      fullPath: "/products/$handle";
      preLoaderRoute: typeof routesProductRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collections/$handle": {
      id: "/collections/$handle";
      path: "/collections/$handle";
      fullPath: "/collections/$handle";
      preLoaderRoute: typeof routesCollectionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  routesHomeRoute: routesHomeRoute,
  routesCatchallRoute: routesCatchallRoute,
  routesAccountRoute: routesAccountRoute,
  routesCartRoute: routesCartRoute,
  routesCollectionsRoute: routesCollectionsRoute,
  routesRobotsRoute: routesRobotsRoute,
  routesSearchRoute: routesSearchRoute,
  routesSitemapRoute: routesSitemapRoute,
  routesCollectionRoute: routesCollectionRoute,
  routesProductRoute: routesProductRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
