import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {graphql} from '../gql/gql';
import {request} from 'graphql-request';
import type {GetServerSideProps} from 'next';
import {shopClient} from '../src/shopify-client';
import type {ProductQuery} from '../gql/graphql';
import {
  type StorefrontApiResponseOk,
  useShop,
  AnalyticsPageType,
  sendShopifyAnalytics,
  AnalyticsEventName,
  getClientBrowserParameters,
  type ShopifyAddToCartPayload,
  ShopifyAnalyticsProduct,
  ShopifyAnalyticsPayload,
} from '@shopify/hydrogen-react';
import Link from 'next/link';

export const getServerSideProps: GetServerSideProps = async () => {
  // @TODO figure out how to get the client's IP address correctly and accurately.
  // const buyerIp =
  //   req.headers["x-real-ip"] ??
  //   req.headers["x-forwarded-for"] ??
  //   req.socket.remoteAddress;

  try {
    const response = await request({
      url: shopClient.getStorefrontApiUrl(),
      document: query,
      // @TODO: convert to 'getPrivateTokenHeaders({buyerIp})'
      requestHeaders: shopClient.getPublicTokenHeaders(),
    });

    const product = response.products.nodes[0];
    const variant = product.variants.nodes[0];

    const productAnalytics: ShopifyAnalyticsProduct = {
      productGid: product.id,
      variantGid: variant.id,
      name: product.title,
      variantName: variant.title,
      brand: product.vendor,
      price: variant.price.amount,
    };

    // @TODO I don't love how we do this with 'errors' and 'data'
    return {
      props: {
        data: response,
        errors: null,
        analytics: {
          pageType: AnalyticsPageType.product,
          resourceId: product.id,
          products: [productAnalytics],
        },
      },
    };
  } catch (err) {
    console.error(err);
    return {props: {data: null, errors: [(err as Error).toString()]}};
  }
};

export default function Product({
  data,
  errors,
  analytics,
}: StorefrontApiResponseOk<ProductQuery> & {
  analytics: ShopifyAnalyticsPayload;
}) {
  const {storeDomain} = useShop();

  if (!data || errors) {
    console.error(errors);
    return <div>Whoops there was an error! Please refresh and try again.</div>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Product Page</h1>
        <div>Storefront API Domain: {storeDomain}</div>
        <br />
        <button
          onClick={() => {
            if (analytics.products) {
              const payload: ShopifyAddToCartPayload = {
                ...getClientBrowserParameters(),
                ...analytics,
                cartId: 'abc123',
                products: [
                  {
                    ...analytics.products[0],
                    quantity: 1,
                  },
                ],
              };
              sendShopifyAnalytics({
                eventName: AnalyticsEventName.ADD_TO_CART,
                payload,
              });
            }
          }}
        >
          Analytics - Add to cart
        </button>
        <br />
        <Link href="/">Back to Home</Link>
        <Link href="/collection">Go to Collection</Link>
        <Link href="/search">Go to Search</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=hydrogen-react-monorepo"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

const query = graphql(`
  query Product {
    shop {
      name
    }
    products(first: 1) {
      nodes {
        # if you uncomment 'blah', it should have a GraphQL validation error in your IDE if you have a GraphQL plugin. It should also give an error during 'npm run dev'
        # blah
        id
        title
        vendor
        publishedAt
        handle
        variants(first: 1) {
          nodes {
            id
            title
            price {
              amount
            }
            image {
              url
              altText
              width
              height
            }
          }
        }
      }
    }
  }
`);
