# yaml-language-server: $schema=../../recipe.schema.json

gid: 8495ffc3-e69c-431a-ac0b-1abb16ab50a2
title: Bundles
summary: Display product bundles on your Hydrogen storefront.
description: |
  This recipe adds special styling for product bundles on your Hydrogen
  storefront. Customers will see badges and relevant cover images for bundles
  when they're viewing product and collection pages.

  In this recipe you'll make the following changes:

  1. Set up the Shopify Bundles app in your Shopify admin and create a new
  product bundle.
  2. Update the GraphQL fragments to query for bundles to identify bundled
  products.
  3. Update the product and collection templates to display badges on product
  listings, update the copy for the cart buttons, and display bundle-specific
  information on product and collection pages.
  4. Update the cart line item template to display the bundle badge as needed.
notes: []
requirements: |
  To use product bundles, you need to install a bundles app in your Shopify admin.
  In this recipe, we'll use the [Shopify Bundles app](https://apps.shopify.com/shopify-bundles).
ingredients:
  - path: templates/skeleton/app/components/BundleBadge.tsx
    description: A badge displayed on bundle product listings.
  - path: templates/skeleton/app/components/BundledVariants.tsx
    description: A component that wraps the variants of a bundle product in a single
      product listing.
deletedFiles: []
steps:
  - type: INFO
    step: "1"
    name: Set up the Shopify Bundles app
    description: |
      1. Install the [Shopify Bundles app](https://apps.shopify.com/shopify-bundles) in your Shopify admin.

      2. Make sure your store meets the [eligibility requirements](https://help.shopify.com/en/manual/products/bundles/eligibility-and-considerations).

      3. From the [**Bundles**](https://admin.shopify.com/apps/shopify-bundles/app) page, [create a new bundle](https://help.shopify.com/en/manual/products/bundles/shopify-bundles).
  - type: NEW_FILE
    step: "2"
    name: Create the BundleBadge component
    description: |
      Create a new BundleBadge component to be displayed on bundle product listings.
    ingredients:
      - path: templates/skeleton/app/components/BundleBadge.tsx
  - type: NEW_FILE
    step: "3"
    name: Create a new BundledVariants component
    description: Create a new `BundledVariants` component that wraps the variants of
      a bundle product in a single product listing.
    ingredients:
      - path: templates/skeleton/app/components/BundledVariants.tsx
  - type: PATCH
    step: "4"
    name: Query bundle pricing for recommended products
    description: |
      Add `maxVariantPrice` to the `RecommendedProducts` query's product fields.
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.243e26.patch
  - type: PATCH
    step: "5"
    name: Show bundled products on the product page
    description: |
      1. Add the `requiresComponents` field to the `Product` fragment, which is
      used to identify bundled products.
      2. Pass the `isBundle` flag to the `ProductImage` component.
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.6f2e82.patch
  - type: PATCH
    step: "6"
    name: Detect bundles in collection listings
    description: |
      Like the previous step, use the `requiresComponents` field to detect if the product item is a bundle.
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.f062a9.patch
  - type: PATCH
    step: "7"
    name: Identify bundles in the cart
    description: |
      Use the `requiresComponents` field to determine if a cart line item is a bundle.
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.026109.patch
  - type: PATCH
    step: "8"
    name: Show bundle badges in the cart
    description: |
      If a product is a bundle, show the `BundleBadge` component in the cart line item.
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.2c9a50.patch
  - type: PATCH
    step: "9"
    name: Update the cart button text for bundles
    description: |
      If a product is a bundle, update the text of the product button.
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.649d3b.patch
  - type: PATCH
    step: "10"
    name: Show bundle badges on product images
    description: |
      If a product is a bundle, show the `BundleBadge` component in the `ProductImage` component.
    diffs:
      - file: app/components/ProductImage.tsx
        patchFile: ProductImage.tsx.42c3b6.patch
  - type: PATCH
    step: "11"
    name: Show bundle badges on product cards
    description: |
      If a product is a bundle, show the `BundleBadge` component in the `ProductItem` component.
    diffs:
      - file: app/components/ProductItem.tsx
        patchFile: ProductItem.tsx.d3223b.patch
  - type: PATCH
    step: "12"
    name: Position bundle badges on images
    description: |
      Make sure the bundle badge is positioned relative to the product image.
    diffs:
      - file: app/styles/app.css
        patchFile: app.css.881a99.patch
nextSteps: |
  - Test your implementation by going to your store and adding a bundle to the cart. Make sure that the bundle's badge appears on the product page and in the cart.
  - (Optional) [Place a test order](https://help.shopify.com/en/manual/checkout-settings/test-orders) to see how orders for bundles appear in your Shopify admin.
llms:
  userQueries:
    - How do I show product bundles on my Hydrogen storefront?
    - How do I add badges to bundled products on my Hydrogen storefront?
    - How do I display product bundles on applicable line items in the cart?
    - How do I detect if a product is a bundle?
  troubleshooting:
    - issue: I'm not seeing product bundles on my storefront.
      solution: Make sure you've installed the Shopify Bundles app and set up product
        bundles in your Shopify admin.
    - issue: I'm not seeing product bundle badges on product pages.
      solution: Make sure you've installed the Shopify Bundles app and set up product
        bundles in your Shopify admin. Then make sure you've updated the product
        fragment to query for bundles and display BundledVariants.
    - issue: I'm not seeing the product bundle badges on my cart line items.
      solution: Make sure you've installed the Shopify Bundles app and set up product
        bundles in your Shopify admin. Then make sure you've updated the cart
        fragment to query for bundles.
commit: 4f5db289f8a9beb5c46dda9416a7ae8151f7e08e
