# yaml-language-server: $schema=../../recipe.schema.json

title: Bundles
summary: ""
description: ""
notes: []
requirements: null
ingredients:
  - path: templates/skeleton/app/components/BundleBadge.tsx
    description: null
  - path: templates/skeleton/app/components/BundledVariants.tsx
    description: null
deletedFiles: []
steps:
  - type: COPY_INGREDIENTS
    index: 1
    name: Add ingredients to your project
    description: Copy all the files found in the `ingredients/` directory into your project.
    ingredients:
      - templates/skeleton/app/components/BundleBadge.tsx
      - templates/skeleton/app/components/BundledVariants.tsx
  - type: PATCH
    index: 2
    name: Conditionally render the `BundleBadge` in Cart lines
    description: null
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.f93ff4.patch
  - type: PATCH
    index: 3
    name: Conditionally render "Add bundle to cart" in ProductForm
    description: null
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.252e88.patch
  - type: PATCH
    index: 4
    name: Conditionally render the `BundleBadge in ProductImage
    description: null
    diffs:
      - file: app/components/ProductImage.tsx
        patchFile: ProductImage.tsx.ac6815.patch
  - type: PATCH
    index: 5
    name: Conditionally render the BundleBadge in ProductItem
    description: null
    diffs:
      - file: app/components/ProductItem.tsx
        patchFile: ProductItem.tsx.f84e8c.patch
  - type: PATCH
    index: 6
    name: Update the Cart fragment to query for bundles
    description: null
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: PATCH
    index: 7
    name: Update collections fragment to query for bundles
    description: null
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.c46c36.patch
  - type: PATCH
    index: 8
    name: Update product fragment to query for bundles and display `BundledVariants`
    description: null
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.7addea.patch
  - type: PATCH
    index: 9
    name: Add a product-image class to the app stylesheet
    description: null
    diffs:
      - file: app/styles/app.css
        patchFile: app.css.48239a.patch
llms:
  userQueries: []
  troubleshooting: []
commit: 658f0c7ed75d10c0789d426a1dbc771e31a6c2a9
