# yaml-language-server: $schema=../../recipe.schema.json

title: bundles
summary: ''
description: ''
notes: []
requirements: null
ingredients: []
deletedFiles: []
steps:
  - type: PATCH
    index: 1
    name: app/components/CartLineItem.tsx
    description: null
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.f93ff4.patch
  - type: PATCH
    index: 2
    name: app/components/ProductForm.tsx
    description: null
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.252e88.patch
  - type: PATCH
    index: 3
    name: app/components/ProductImage.tsx
    description: null
    diffs:
      - file: app/components/ProductImage.tsx
        patchFile: ProductImage.tsx.ac6815.patch
  - type: PATCH
    index: 4
    name: app/lib/fragments.ts
    description: null
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: PATCH
    index: 5
    name: app/routes/cart.tsx
    description: null
    diffs:
      - file: app/routes/cart.tsx
        patchFile: cart.tsx.943271.patch
  - type: PATCH
    index: 6
    name: app/routes/collections.$handle.tsx
    description: null
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.c46c36.patch
  - type: PATCH
    index: 7
    name: app/routes/collections.all.tsx
    description: null
    diffs:
      - file: app/routes/collections.all.tsx
        patchFile: collections.all.tsx.df435d.patch
  - type: PATCH
    index: 8
    name: app/routes/products.$handle.tsx
    description: null
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.7addea.patch
  - type: PATCH
    index: 9
    name: app/styles/app.css
    description: null
    diffs:
      - file: app/styles/app.css
        patchFile: app.css.48239a.patch
commit: 61ddf92487524b3c04632ae2cfdaa2869a3ae02c
