# yaml-language-server: $schema=../../recipe.schema.json

gid: 8f841505-d7e2-488d-87d1-4500e6bf0738
title: footer
summary: Add a footer menu to your Hydrogen store
description: |
  This recipe lets you add a footer menu to your Hydrogen store

  In this recipe you'll make the following changes:

  1. Set up a footer menu in the admin
  2. Modify the root layout to query for the footer menu
  3. Add a <Footer /> component display the footer links
  4. Display the footer inside the <PageLayout />
notes: []
requirements: |
  To implement a footer menu in your own store, you need to create a menu in the Shopify admin with the handle of `skeleton-footer-menu` at https://admin.shopify.com/store/YOUR_STORE_DOMAIN/content/menus
ingredients:
  - path: templates/skeleton/app/components/Footer.tsx
    description: null
deletedFiles: []
steps:
  - type: PATCH
    step: "1"
    name: Render the <Footer /> component in the <PageLayout />
    description: null
    diffs:
      - file: app/components/PageLayout.tsx
        patchFile: PageLayout.tsx.130b44.patch
  - type: NEW_FILE
    step: "1"
    name: Create the <Footer /> component
    description: null
    ingredients:
      - path: templates/skeleton/app/components/Footer.tsx
  - type: PATCH
    step: "2"
    name: Add the footer MENU GraphQL query
    description: null
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: PATCH
    step: "3"
    name: Asynchronously query the Footer menu at the root layout
    description: null
    diffs:
      - file: app/root.tsx
        patchFile: root.tsx.8c182c.patch
nextSteps: null
llms:
  userQueries:
    - How can I add a footer to my Hydrogen store?
    - Help me add a hydrogen footer menu to my store
    - I want to display some links at the bottom of my hydrogen store?,
  troubleshooting:
    - issue: I can see a black bar, but there are no links inside
      solution: Make sure you've configured a menu in the Shopify admin with the
        handle of `skeleton-footer-menu` at
        https://admin.shopify.com/store/YOUR_STORE_DOMAIN/content/menus
commit: 3dbbb1ee554d96261a2249d8126c8afd11e7ad47
