# yaml-language-server: $schema=../../recipe.schema.json

gid: 8f841505-d7e2-488d-87d1-4500e6bf0738
title: footer
summary: ""
description: ""
notes: []
requirements: null
ingredients: []
deletedFiles: []
steps: []
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 3dbbb1ee554d96261a2249d8126c8afd11e7ad47
