name: hydrogen
display_name: Hydrogen

up:
  - node: 'v24.13.0' # .nvmrc uses 'v24' for nvm flexibility; dev tool needs specific version
  - packages:
      - ejson
  - custom:
      name: Build packages
      met?: pnpm run build
      meet: 'true'

# So the Shopify CLI loads the local @shopify/cli-hydrogen plugin when running
# commands (e.g. skeleton dev → shopify hydrogen dev) instead of the bundled one.
env:
  SHOPIFY_CLI_ENV: development

commands:
  server:
    desc: 'Run the skeleton template dev server'
    run: pnpm run build && pnpm run dev:app

  # Standard development commands
  watch:
    desc: 'Run a server to watch for changes in any packages and automatically rebuild when changes are saved'
    run: pnpm run dev

  build:
    desc: 'Build packages for production distribution'
    run: pnpm run build

  test:
    desc: 'Run tests once'
    run: pnpm run test
    aliases: [t]

  test-watch:
    desc: 'Run tests in watch mode'
    run: pnpm run test:watch

  typecheck:
    desc: 'Check source-code for invalid TypeScript'
    run: pnpm run typecheck

  lint:
    desc: 'Lint the code with ESLint'
    run: pnpm run lint

  format:
    desc: 'Format the code with prettier'
    run: pnpm run format

  changeset:
    desc: 'Add a changeset for releases'
    run: pnpm run changeset add

  cookbook:
    subcommands:
      regenerate:
        desc: 'Refresh all cookbook recipes'
        run: pnpm --dir cookbook run cookbook -- regenerate
      validate:
        desc: 'Validate all cookbook recipes'
        run: pnpm --dir cookbook run cookbook -- validate

  # Package-specific commands
  hydrogen:
    subcommands:
      dev:
        desc: 'Run Hydrogen package in dev mode'
        run: pnpm --dir packages/hydrogen run dev
      build:
        desc: 'Build Hydrogen package'
        run: pnpm --dir packages/hydrogen run build
      docs:
        desc: 'Build Hydrogen documentation'
        run: pnpm --dir packages/hydrogen run build-docs

  skeleton:
    subcommands:
      dev:
        desc: 'Run skeleton template in dev mode'
        run: pnpm --dir templates/skeleton run dev
      dev-tunnel:
        desc: 'Run skeleton template in dev mode with tunnel'
        run: SHOPIFY_HYDROGEN_FLAG_CUSTOMER_ACCOUNT_PUSH=true pnpm --dir templates/skeleton run dev
      build:
        desc: 'Build skeleton template'
        run: pnpm --dir templates/skeleton run build

open:
  github: https://github.com/Shopify/hydrogen
  pr: # Opens PR for current branch
  issues: # Opens GitHub issues
  docs: https://shopify.dev/docs/api/hydrogen
  hydrogen-react-docs: https://shopify.dev/docs/api/hydrogen-react
