packages:
  - cookbook
  - docs/preview
  - packages/cli
  - packages/create-hydrogen
  - packages/hydrogen-codegen
  - packages/hydrogen-react
  - packages/hydrogen
  - packages/mini-oxygen
  - packages/remix-oxygen
  - templates/skeleton

catalog:
  '@types/node': '^22'
  '@types/react': '^18.3.28'
  '@types/react-dom': '^18.3.7'
  react: '^18.3.1'
  react-dom: '^18.3.1'
