packages:
  - cookbook
  - docs/preview
  - packages/cli
  - packages/create-hydrogen
  - packages/hydrogen-codegen
  - packages/hydrogen-react
  - packages/hydrogen
  - packages/mini-oxygen
  - packages/remix-oxygen
  - templates/skeleton

overrides:
  '@oclif/core': '3.26.5'
  '@shopify/cli-kit': '3.80.4'
  form-data: '>=4.0.4'
  '@types/node': 'catalog:'
  cookie: '^0.7.0'

catalog:
  '@types/node': '^22'
  '@types/react': '^18.3.28'
  '@types/react-dom': '^18.3.7'
  react: '^18.3.1'
  react-dom: '^18.3.1'
  '@shopify/prettier-config': '^1.1.2'
