#!/usr/bin/env node
/**
 * Builds single-file Playwright bundles of the new-cookies consent specs,
 * ready to upload into Observe Synthetic Checks
 * (https://observe.shopify.io/a/observe/monitoring/synthetic).
 *
 * The Observe runner executes each bundle as a standalone Playwright test
 * file against deployed storefronts: no dev server, no playwright.config,
 * no ejson. Everything the specs need from the repo environment is baked in
 * here:
 *
 * - `E2E_OBSERVE_STORE_URLS`: map of test store key -> deployed storefront
 *   URL (see e2e/fixtures/observe.ts). Specs that spawn a local dev server
 *   locally instead navigate to the deployment.
 * - `E2E_LOADTEST_HEADER`: the bot-priority header name from secrets.ejson,
 *   applied to every request like the repo playwright.config does.
 *
 * Usage:
 *   HYDROGEN_E2E_OBSERVE_STORE_URLS='{"defaultConsentAllowed_cookiesEnabled":"https://…"}' \
 *   pnpm e2e:observe:build [--only <substring>]
 *
 * Or pass the map directly: pnpm e2e:observe:build -- --store-urls '<json>'
 */

import {execFileSync} from 'node:child_process';
import {existsSync, readFileSync, renameSync} from 'node:fs';
import {basename, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';

const repoRoot = resolve(fileURLToPath(import.meta.url), '../../..');
const metadataPath = resolve(repoRoot, 'e2e/observe/metadata.json');
const distDir = resolve(repoRoot, 'e2e/observe/dist');

/** Local-only store modes that cannot run against a deployment. */
const NON_DEPLOYABLE_STORE_KEYS = ['mockShop'];

/** Every store key a new-cookies spec may reference. */
const DEPLOYABLE_STORE_KEYS = [
  'defaultConsentAllowed_cookiesEnabled',
  'defaultConsentDisallowed_cookiesEnabled',
  'hydrogenPreviewStorefront',
  'customerAccount',
];

function parseArgs() {
  const args = process.argv.slice(2);
  const value = (flag) => {
    const index = args.indexOf(flag);
    return index === -1 ? undefined : args[index + 1];
  };
  return {
    storeUrls:
      value('--store-urls') ?? process.env.HYDROGEN_E2E_OBSERVE_STORE_URLS,
    loadtestHeader:
      value('--loadtest-header') ?? process.env.HYDROGEN_E2E_LOADTEST_HEADER,
    only: value('--only'),
  };
}

/** The loadtest header name from secrets.ejson (its value is always 'true'). */
function loadtestHeaderFromEjson() {
  if (!existsSync(resolve(repoRoot, 'secrets.ejson'))) return undefined;
  const decrypted = execFileSync('ejson', ['decrypt', 'secrets.ejson'], {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  return JSON.parse(decrypted)['e2e-testing']?.loadtest_header;
}

/**
 * Validate that every store key the spec references has a deployment URL,
 * and return the full baked URL map (multi-store specs resolve every key).
 */
function bakedStoreUrls(specSource, specFile, storeUrlMap) {
  const referencedKeys = [...NON_DEPLOYABLE_STORE_KEYS, ...DEPLOYABLE_STORE_KEYS]
    .filter((storeKey) => specSource.includes(`'${storeKey}'`));

  const nonDeployable = referencedKeys.filter((storeKey) =>
    NON_DEPLOYABLE_STORE_KEYS.includes(storeKey),
  );
  if (nonDeployable.length > 0) {
    throw new Error(
      `${specFile} uses local-only store key(s) ${nonDeployable.join(', ')}; ` +
        'it cannot run as an Observe synthetic check',
    );
  }

  const missingUrls = referencedKeys.filter((key) => !storeUrlMap[key]);
  if (missingUrls.length > 0) {
    throw new Error(
      `No deployment URL for store key(s) ${missingUrls.join(', ')} ` +
        `(used by ${specFile}); add them to the store URL map`,
    );
  }

  return JSON.stringify(
    Object.fromEntries(
      DEPLOYABLE_STORE_KEYS.filter((key) => storeUrlMap[key]).map((key) => [
        key,
        storeUrlMap[key],
      ]),
    ),
  );
}

function banner(relativeSpecPath, gitHash) {
  const esmDirnameShim = [
    '// The bundled fixtures use __dirname in dev-server-only code paths; the',
    '// values are never read when running against a deployment.',
    'import {fileURLToPath} from "node:url";',
    'var __dirname = fileURLToPath(new URL(".", import.meta.url));',
    '',
  ].join('\n');

  return `/*
DO NOT EDIT THIS FILE DIRECTLY

Edit on GitHub here: https://github.com/Shopify/hydrogen/edit/main/${relativeSpecPath}

Syncing to Observe is manual: merging a change to main does NOT update this synthetic.
After changing the test, run: pnpm e2e:observe:sync ${relativeSpecPath}
Permalink to this version: https://github.com/Shopify/hydrogen/blob/${gitHash}/${relativeSpecPath}
*/
${esmDirnameShim}`;
}

/**
 * esbuild is not a direct dependency of the workspace root; resolve it
 * through vite's installation (the same pattern the repo uses to share
 * package-level tooling).
 */
function loadEsbuild() {
  const requireFromHydrogenReact = createRequire(
    resolve(repoRoot, 'packages/hydrogen-react/package.json'),
  );
  const requireFromVite = createRequire(requireFromHydrogenReact.resolve('vite'));
  const esbuild = requireFromVite('esbuild');
  if (typeof esbuild?.build !== 'function') {
    throw new Error('esbuild is unavailable');
  }
  return esbuild;
}

/**
 * The fixtures barrel re-exports two module groups that Observe bundles must
 * not carry:
 *
 * - ./recipe: cookbook tooling that depends on packages not resolvable from
 *   the e2e workspace and is meaningless against a deployment.
 * - ./msw/*: local dev-server request mocking (~1MB of bundled code) that
 *   never activates without a dev server.
 *
 * The consent specs never use either, so observe bundles replace them with
 * stubs. If a spec ever imports one of these exports, the stub fails loudly
 * at call time instead of silently testing nothing.
 */
function devServerOnlyModuleStubPlugin() {
  const MSW_STUB_EXPORTS = `export const MSW_SCENARIOS = {};
export const B2B_COMPANY_NAME = '';
export const LEGACY_CUSTOMER_MOCK = {};
export const STOREFRONT_REDIRECT_PATHS = {};
export const DELIVERY_ADDRESS_SEED_COUNT = 0;
export function getHandlersForScenario() { throw new Error('MSW mocks are not available in Observe bundles'); }
export function mockCustomerAccountOperation() { throw new Error('MSW mocks are not available in Observe bundles'); }`;
  const RECIPE_STUB_EXPORTS = `export const setRecipeFixture = () => { throw new Error('recipe fixtures are not available in Observe bundles'); };`;

  const stubByFilter = new Map([
    [/^\.\/recipe$/, RECIPE_STUB_EXPORTS],
    [/^\.\/msw\/(handlers|graphql|scenarios)$/, MSW_STUB_EXPORTS],
  ]);

  return {
    name: 'observe-dev-server-only-stub',
    setup(build) {
      build.onResolve({filter: /^\.\/(recipe|msw\/\w+)$/}, (args) => {
        for (const [filter, contents] of stubByFilter) {
          if (filter.test(args.path)) {
            return {path: `${args.path}-stub`, namespace: 'observe-stub',};
          }
        }
        return undefined;
      });
      build.onLoad({filter: /.*/, namespace: 'observe-stub'}, (args) => {
        const isMsw = args.path.includes('msw');
        return {
          contents: isMsw ? MSW_STUB_EXPORTS : RECIPE_STUB_EXPORTS,
          loader: 'ts',
        };
      });
    },
  };
}

async function main() {
  const args = parseArgs();

  const storeUrlMap = args.storeUrls ? JSON.parse(args.storeUrls) : undefined;
  if (!storeUrlMap || Object.keys(storeUrlMap).length === 0) {
    console.error(
      '❌ No store URL map. Pass --store-urls <json> or set ' +
        'HYDROGEN_E2E_OBSERVE_STORE_URLS with test store keys mapped to their ' +
        'deployed storefront URLs.',
    );
    process.exit(1);
  }

  const loadtestHeader = args.loadtestHeader ?? loadtestHeaderFromEjson();
  if (!loadtestHeader) {
    console.error(
      '❌ No loadtest header. Pass --loadtest-header <name> or set ' +
        'HYDROGEN_E2E_LOADTEST_HEADER, or configure ejson ' +
        '(scripts/setup-ejson-private-key.sh).',
    );
    process.exit(1);
  }

  const metadata = JSON.parse(readFileSync(metadataPath, 'utf8'));
  const entries = args.only
    ? metadata.filter((entry) => entry.file.includes(args.only))
    : metadata;
  if (entries.length === 0) {
    console.error(
      `❌ No metadata entries${args.only ? ` matching "${args.only}"` : ''}.`,
    );
    process.exit(1);
  }

  const gitHash = execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
    cwd: repoRoot,
    encoding: 'utf8',
  }).trim();
  const esbuild = loadEsbuild();

  for (const entry of entries) {
    const specPath = resolve(repoRoot, entry.file);
    const specSource = readFileSync(specPath, 'utf8');
    const urls = bakedStoreUrls(specSource, entry.file, storeUrlMap);

    // One build per spec so each bundle carries its own source permalink.
    // esbuild can only emit .js, so the bundle is renamed to .mjs (the
    // extension the Observe runner and upload script expect).
    const jsPath = resolve(distDir, `${basename(entry.file, '.ts')}.js`);
    const mjsPath = resolve(distDir, `${basename(entry.file, '.ts')}.mjs`);
    await esbuild.build({
      entryPoints: [specPath],
      bundle: true,
      format: 'esm',
      platform: 'node',
      target: 'esnext',
      keepNames: true,
      minify: false,
      sourcemap: false,
      outdir: distDir,
      entryNames: '[name]',
      external: ['@playwright/test', 'playwright', 'node:*'],
      plugins: [devServerOnlyModuleStubPlugin()],
      define: {
        // Double-encoded: esbuild treats a JSON-parseable define value as an
        // object literal, but the code reads this as a JSON string.
        'process.env.E2E_OBSERVE_STORE_URLS': JSON.stringify(urls),
        'process.env.E2E_LOADTEST_HEADER': JSON.stringify(loadtestHeader),
      },
      banner: {js: banner(entry.file, gitHash)},
      logLevel: 'silent',
    });
    renameSync(jsPath, mjsPath);
    console.log(`✓ ${entry.file} -> e2e/observe/dist/${basename(mjsPath)}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
