# yaml-language-server: $schema=../../recipe.schema.json

gid: 27d7e01b-7264-44e4-ae7c-32dc8da58c46
title: Custom cart method
summary: Add inline product option editing to cart items
description: |
  This recipe implements custom cart methods in Hydrogen using the Storefront API's
  `variantBySelectedOptions` query to let customers edit product options directly
  within the cart. They'll be able to change product variants (like size and color)
  without having to remove items, select different variants, and then add them to
  the cart again. Their cart updates will happen automatically, without requiring
  a full page refresh.

  Key features:
  - Custom cart method `updateLineByOptions` for variant selection
  - Inline dropdown selectors for each product option in cart
  - Automatic cart updates when options are changed
  - Full TypeScript support with proper type augmentation
requirements: |
  - Basic understanding of Hydrogen cart implementation
  - Familiarity with GraphQL and TypeScript
  - Knowledge of React Router actions and forms
  - GraphQL codegen must be run after applying the recipe
ingredients: []
deletedFiles: []
steps:
  - type: PATCH
    step: '1'
    name: README.md
    description: Update the README file with custom cart method documentation and an implementation guide.
    diffs:
      - file: README.md
        patchFile: README.md.db10ed.patch
  - type: PATCH
    step: '2'
    name: app/components/CartLineItem.tsx
    description: Add variant selector functionality to cart line items for changing product options.
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.2c9a50.patch
  - type: PATCH
    step: '3'
    name: app/lib/context.ts
    description: Extend HydrogenCart context with updateLineByOptions method for variant switching.
    diffs:
      - file: app/lib/context.ts
        patchFile: context.ts.1877b3.patch
  - type: PATCH
    step: '4'
    name: app/lib/fragments.ts
    description: Add product options to cart fragments and create PRODUCT_VARIANT_QUERY for fetching variants.
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.026109.patch
  - type: PATCH
    step: '5'
    name: app/routes/cart.tsx
    description: Implement the CustomUpdateLineByOptions action handler for processing variant changes in cart.
    diffs:
      - file: app/routes/cart.tsx
        patchFile: cart.tsx.af0778.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 12374c8f03f82c6800000cf08e327c4db4c287bb
