# yaml-language-server: $schema=../../recipe.schema.json

gid: 27d7e01b-7264-44e4-ae7c-32dc8da58c46
title: Custom Cart Method
summary: Add inline product option editing to cart items
description: |
  This recipe demonstrates how to implement custom cart methods in Hydrogen to enable inline editing of product options directly within the cart. Users can change product variants (size, color, etc.) without removing and re-adding items.

  Key features:
  - Custom cart method `updateLineByOptions` for variant selection
  - Inline dropdown selectors for each product option in cart
  - Automatic cart updates when options are changed
  - Full TypeScript support with proper type augmentation
notes:
  - This implementation requires GraphQL codegen to be run after applying the
    recipe
  - The custom cart method uses the Storefront API's variantBySelectedOptions
    query
  - Cart updates happen automatically on option change without page refresh
requirements: |
  - Basic understanding of Hydrogen cart implementation
  - Familiarity with GraphQL and TypeScript
  - Knowledge of React Router actions and forms
ingredients: []
deletedFiles: []
steps:
  - type: PATCH
    step: 1
    name: README.md
    description: Updates README with custom cart method documentation and implementation guide
    diffs:
      - file: README.md
        patchFile: README.md.49f8fa.patch
  - type: PATCH
    step: 2
    name: app/components/CartLineItem.tsx
    description: Adds variant selector functionality to cart line items for changing product options
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.f93ff4.patch
  - type: PATCH
    step: 3
    name: app/lib/context.ts
    description: Extends HydrogenCart context with updateLineByOptions method for variant switching
    diffs:
      - file: app/lib/context.ts
        patchFile: context.ts.cfd9da.patch
  - type: PATCH
    step: 4
    name: app/lib/fragments.ts
    description: Adds product options to cart fragments and creates PRODUCT_VARIANT_QUERY for fetching variants
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: PATCH
    step: 5
    name: app/routes/cart.tsx
    description: Implements CustomUpdateLineByOptions action handler for processing variant changes in cart
    diffs:
      - file: app/routes/cart.tsx
        patchFile: cart.tsx.943271.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 6681f92e84d42b5a6aca153fb49e31dcd8af84f6
