# yaml-language-server: $schema=../../recipe.schema.json

gid: 5e5f8934-e836-4b4c-aa60-30b5f45944f9
title: Dynamic Content with Metaobjects
summary: Build a flexible CMS using Shopify metaobjects for dynamic content sections
description: |
  This recipe demonstrates how to create a content management system using Shopify metaobjects.
  It enables merchants to create and manage dynamic content sections through the Shopify admin,
  providing a flexible way to build pages with reusable components.

  Key features:
  - Dynamic route-based content rendering
  - Modular section components (Hero, Featured Products, Featured Collections, Stores)
  - Content editing capabilities with direct links to Shopify admin
  - Rich text support with Slate editor
  - Comprehensive documentation with visual guides

  The recipe includes example section components that can be customized or extended
  to match your specific content needs.
notes:
  - You need to create the metaobject definitions in your Shopify admin before
    using this recipe
  - See the included guides/metaobjects/README.md for detailed setup instructions
  - Each section component has a one-to-one relationship with a metaobject
    definition
  - The PUBLIC_STORE_DOMAIN environment variable is required for edit links to
    work
requirements: |
  - Basic understanding of Shopify metaobjects
  - Shopify Plus or development store (for metaobjects access)
  - Environment variable: PUBLIC_STORE_DOMAIN (your store's admin domain)
ingredients:
  - path: templates/skeleton/app/components/EditRoute.tsx
    description: null
  - path: templates/skeleton/app/routes/stores.$name.tsx
    description: null
  - path: templates/skeleton/app/routes/stores._index.tsx
    description: null
  - path: templates/skeleton/app/sections/RouteContent.tsx
    description: null
  - path: templates/skeleton/app/sections/SectionFeaturedCollections.tsx
    description: null
  - path: templates/skeleton/app/sections/SectionFeaturedProducts.tsx
    description: null
  - path: templates/skeleton/app/sections/SectionHero.tsx
    description: null
  - path: templates/skeleton/app/sections/SectionStoreProfile.tsx
    description: null
  - path: templates/skeleton/app/sections/SectionStores.tsx
    description: null
  - path: templates/skeleton/app/sections/Sections.tsx
    description: null
  - path: templates/skeleton/app/utils/parseSection.ts
    description: null
  - path: templates/skeleton/guides/metaobjects/README.md
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_link.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_featured_collections.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_featured_products.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_hero.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_rich_text.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_store_profile.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_section_stores_grid.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definition_store.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definitions_list.png
    description: null
  - path: templates/skeleton/guides/metaobjects/images/definiton_route.png
    description: null
deletedFiles: []
steps:
  - type: PATCH
    step: 1
    name: README.md
    description: Updates README with metaobjects CMS documentation and architecture overview
    diffs:
      - file: README.md
        patchFile: README.md.49f8fa.patch
  - type: PATCH
    step: 2
    name: app/lib/fragments.ts
    description: Adds RECOMMENDED_PRODUCT_FRAGMENT for displaying product
      collections in metaobject sections
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: NEW_FILE
    step: 3
    name: app/components/EditRoute.tsx
    description:
      Adds edit route component for managing metaobject-based content in
      development
    ingredients:
      - path: templates/skeleton/app/components/EditRoute.tsx
  - type: PATCH
    step: 4
    name: app/root.tsx
    description:
      Exposes public store subdomain for metaobject queries and content
      management
    diffs:
      - file: app/root.tsx
        patchFile: root.tsx.8c182c.patch
  - type: NEW_FILE
    step: 4
    name: app/routes/stores.$name.tsx
    description: Dynamic store profile route displaying store-specific metaobject content
    ingredients:
      - path: templates/skeleton/app/routes/stores.$name.tsx
  - type: PATCH
    step: 5
    name: app/routes/_index.tsx
    description: Integrates RouteContent component to render metaobject sections on homepage
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.ee5996.patch
  - type: NEW_FILE
    step: 6
    name: app/routes/stores._index.tsx
    description: Store listing page showing all stores from metaobjects with grid layout
    ingredients:
      - path: templates/skeleton/app/routes/stores._index.tsx
  - type: PATCH
    step: 7
    name: package.json
    description: Adds Slate dependencies for rich text editing in metaobject sections
    diffs:
      - file: package.json
        patchFile: package.json.47be7b.patch
  - type: NEW_FILE
    step: 8
    name: app/sections/RouteContent.tsx
    description: Main component for fetching and rendering metaobject-based route content
    ingredients:
      - path: templates/skeleton/app/sections/RouteContent.tsx
  - type: NEW_FILE
    step: 9
    name: app/sections/SectionFeaturedCollections.tsx
    description:
      Section component for displaying featured product collections from
      metaobjects
    ingredients:
      - path: templates/skeleton/app/sections/SectionFeaturedCollections.tsx
  - type: NEW_FILE
    step: 10
    name: app/sections/SectionFeaturedProducts.tsx
    description: Section component for showcasing featured products with customizable layout
    ingredients:
      - path: templates/skeleton/app/sections/SectionFeaturedProducts.tsx
  - type: NEW_FILE
    step: 11
    name: app/sections/SectionHero.tsx
    description:
      Hero banner section with image, heading, and call-to-action from
      metaobjects
    ingredients:
      - path: templates/skeleton/app/sections/SectionHero.tsx
  - type: NEW_FILE
    step: 12
    name: app/sections/SectionStoreProfile.tsx
    description:
      Store profile section displaying store details, hours, and contact
      information
    ingredients:
      - path: templates/skeleton/app/sections/SectionStoreProfile.tsx
  - type: NEW_FILE
    step: 13
    name: app/sections/SectionStores.tsx
    description:
      Grid layout section for displaying multiple store locations from
      metaobjects
    ingredients:
      - path: templates/skeleton/app/sections/SectionStores.tsx
  - type: NEW_FILE
    step: 14
    name: app/sections/Sections.tsx
    description: Dynamic section renderer that maps metaobject types to React components
    ingredients:
      - path: templates/skeleton/app/sections/Sections.tsx
  - type: NEW_FILE
    step: 15
    name: app/utils/parseSection.ts
    description: Utility function for parsing and transforming metaobject field data
    ingredients:
      - path: templates/skeleton/app/utils/parseSection.ts
  - type: NEW_FILE
    step: 16
    name: guides/metaobjects/README.md
    description: Comprehensive guide for setting up metaobject definitions in Shopify admin
    ingredients:
      - path: templates/skeleton/guides/metaobjects/README.md
  - type: NEW_FILE
    step: 17
    name: guides/metaobjects/images/definition_link.png
    description: Screenshot showing Link metaobject field configuration
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_link.png
  - type: NEW_FILE
    step: 18
    name: guides/metaobjects/images/definition_section_featured_collections.png
    description: Screenshot of Featured Collections section metaobject definition
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_featured_collections.png
  - type: NEW_FILE
    step: 19
    name: guides/metaobjects/images/definition_section_featured_products.png
    description: Screenshot of Featured Products section metaobject definition
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_featured_products.png
  - type: NEW_FILE
    step: 20
    name: guides/metaobjects/images/definition_section_hero.png
    description: Screenshot of Hero section metaobject definition with image and text fields
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_hero.png
  - type: NEW_FILE
    step: 21
    name: guides/metaobjects/images/definition_section_rich_text.png
    description: Screenshot of Rich Text section metaobject definition
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_rich_text.png
  - type: NEW_FILE
    step: 22
    name: guides/metaobjects/images/definition_section_store_profile.png
    description: Screenshot of Store Profile section metaobject definition
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_store_profile.png
  - type: NEW_FILE
    step: 23
    name: guides/metaobjects/images/definition_section_stores_grid.png
    description: Screenshot of Stores Grid section metaobject definition
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_section_stores_grid.png
  - type: NEW_FILE
    step: 24
    name: guides/metaobjects/images/definition_store.png
    description: Screenshot of Store metaobject definition with location and contact fields
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definition_store.png
  - type: NEW_FILE
    step: 25
    name: guides/metaobjects/images/definitions_list.png
    description: Screenshot showing list of all metaobject definitions in Shopify admin
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definitions_list.png
  - type: NEW_FILE
    step: 26
    name: guides/metaobjects/images/definiton_route.png
    description: Screenshot of Route metaobject definition with sections reference field
    ingredients:
      - path: templates/skeleton/guides/metaobjects/images/definiton_route.png
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 75623a5bfdd8d6f0eab0d3547860341c20d9076c
