import * as Types from '@shopify/hydrogen-react/storefront-api-types';

/**
 * This file is automatically generated. Do not modify directly; instead, update the associated query that lives next to this file and run the `codegen` script again.
 **/

export type HomepageSeoQueryVariables = Types.Exact<{
  handle?: Types.InputMaybe<Types.Scalars['String']>;
  country?: Types.InputMaybe<Types.CountryCode>;
  language?: Types.InputMaybe<Types.LanguageCode>;
}>;

export type HomepageSeoQuery = {
  __typename?: 'QueryRoot';
  hero?: {
    __typename?: 'Collection';
    id: string;
    handle: string;
    title: string;
    descriptionHtml: string;
    heading?: {__typename?: 'Metafield'; value: string} | null;
    byline?: {__typename?: 'Metafield'; value: string} | null;
    cta?: {__typename?: 'Metafield'; value: string} | null;
    spread?: {
      __typename?: 'Metafield';
      reference?:
        | {__typename?: 'Collection'}
        | {__typename?: 'GenericFile'}
        | {
            __typename: 'MediaImage';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            image?: {
              __typename?: 'Image';
              url: string;
              width?: number | null;
              height?: number | null;
            } | null;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | {__typename?: 'Page'}
        | {__typename?: 'Product'}
        | {__typename?: 'ProductVariant'}
        | {
            __typename: 'Video';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            sources: Array<{
              __typename?: 'VideoSource';
              mimeType: string;
              url: string;
            }>;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | null;
    } | null;
    spreadSecondary?: {
      __typename?: 'Metafield';
      reference?:
        | {__typename?: 'Collection'}
        | {__typename?: 'GenericFile'}
        | {
            __typename: 'MediaImage';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            image?: {
              __typename?: 'Image';
              url: string;
              width?: number | null;
              height?: number | null;
            } | null;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | {__typename?: 'Page'}
        | {__typename?: 'Product'}
        | {__typename?: 'ProductVariant'}
        | {
            __typename: 'Video';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            sources: Array<{
              __typename?: 'VideoSource';
              mimeType: string;
              url: string;
            }>;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | null;
    } | null;
  } | null;
  shop: {__typename?: 'Shop'; name: string; description?: string | null};
};

export type CollectionHeroQueryVariables = Types.Exact<{
  handle?: Types.InputMaybe<Types.Scalars['String']>;
  country?: Types.InputMaybe<Types.CountryCode>;
  language?: Types.InputMaybe<Types.LanguageCode>;
}>;

export type CollectionHeroQuery = {
  __typename?: 'QueryRoot';
  hero?: {
    __typename?: 'Collection';
    id: string;
    handle: string;
    title: string;
    descriptionHtml: string;
    heading?: {__typename?: 'Metafield'; value: string} | null;
    byline?: {__typename?: 'Metafield'; value: string} | null;
    cta?: {__typename?: 'Metafield'; value: string} | null;
    spread?: {
      __typename?: 'Metafield';
      reference?:
        | {__typename?: 'Collection'}
        | {__typename?: 'GenericFile'}
        | {
            __typename: 'MediaImage';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            image?: {
              __typename?: 'Image';
              url: string;
              width?: number | null;
              height?: number | null;
            } | null;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | {__typename?: 'Page'}
        | {__typename?: 'Product'}
        | {__typename?: 'ProductVariant'}
        | {
            __typename: 'Video';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            sources: Array<{
              __typename?: 'VideoSource';
              mimeType: string;
              url: string;
            }>;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | null;
    } | null;
    spreadSecondary?: {
      __typename?: 'Metafield';
      reference?:
        | {__typename?: 'Collection'}
        | {__typename?: 'GenericFile'}
        | {
            __typename: 'MediaImage';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            image?: {
              __typename?: 'Image';
              url: string;
              width?: number | null;
              height?: number | null;
            } | null;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | {__typename?: 'Page'}
        | {__typename?: 'Product'}
        | {__typename?: 'ProductVariant'}
        | {
            __typename: 'Video';
            id: string;
            mediaContentType: Types.MediaContentType;
            alt?: string | null;
            sources: Array<{
              __typename?: 'VideoSource';
              mimeType: string;
              url: string;
            }>;
            previewImage?: {__typename?: 'Image'; url: string} | null;
          }
        | null;
    } | null;
  } | null;
};

export type HomepageFeatureProductsQueryVariables = Types.Exact<{
  country?: Types.InputMaybe<Types.CountryCode>;
  language?: Types.InputMaybe<Types.LanguageCode>;
}>;

export type HomepageFeatureProductsQuery = {
  __typename?: 'QueryRoot';
  products: {
    __typename?: 'ProductConnection';
    nodes: Array<{__typename?: 'Product'}>;
  };
};

export type FeaturedCollectionsQueryVariables = Types.Exact<{
  country?: Types.InputMaybe<Types.CountryCode>;
  language?: Types.InputMaybe<Types.LanguageCode>;
}>;

export type FeaturedCollectionsQuery = {
  __typename?: 'QueryRoot';
  collections: {
    __typename?: 'CollectionConnection';
    nodes: Array<{
      __typename?: 'Collection';
      id: string;
      title: string;
      handle: string;
      image?: {
        __typename?: 'Image';
        altText?: string | null;
        width?: number | null;
        height?: number | null;
        url: string;
      } | null;
    }>;
  };
};
