/**
 * Ambient module declarations for virtual modules used in doc examples.
 * This file must NOT have any top-level imports to remain an ambient declaration file.
 * For module augmentations (extending existing types), use dev-module.env.d.ts instead.
 */

// Generated by React Router (copy-pasted here from skeleton to avoid errors in example files)
declare module 'virtual:react-router/server-build' {
  import {ServerBuild} from 'react-router';
  export const assets: ServerBuild['assets'];
  export const assetsBuildDirectory: ServerBuild['assetsBuildDirectory'];
  export const basename: ServerBuild['basename'];
  export const entry: ServerBuild['entry'];
  export const future: ServerBuild['future'];
  export const isSpaMode: ServerBuild['isSpaMode'];
  export const prerender: ServerBuild['prerender'];
  export const publicPath: ServerBuild['publicPath'];
  export const routeDiscovery: ServerBuild['routeDiscovery'];
  export const routes: ServerBuild['routes'];
  export const ssr: ServerBuild['ssr'];
  export const unstable_getCriticalCss: ServerBuild['unstable_getCriticalCss'];
}
