# yaml-language-server: $schema=../../recipe.schema.json

gid: 9be0e1a5-5337-4343-ac41-1317a48c8d23
title: header
summary: ""
description: ""
notes: []
requirements: null
ingredients:
  - path: templates/skeleton/app/components/Aside.tsx
    description: null
  - path: templates/skeleton/app/components/Header.tsx
    description: null
deletedFiles: []
steps:
  - type: PATCH
    step: "1"
    name: app/components/PageLayout.tsx
    description: null
    diffs:
      - file: app/components/PageLayout.tsx
        patchFile: PageLayout.tsx.130b44.patch
  - type: NEW_FILE
    step: "1"
    name: app/components/Aside.tsx
    description: null
    ingredients:
      - path: templates/skeleton/app/components/Aside.tsx
  - type: PATCH
    step: "2"
    name: app/lib/fragments.ts
    description: null
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.18726b.patch
  - type: NEW_FILE
    step: "2"
    name: app/components/Header.tsx
    description: null
    ingredients:
      - path: templates/skeleton/app/components/Header.tsx
  - type: PATCH
    step: "3"
    name: app/root.tsx
    description: null
    diffs:
      - file: app/root.tsx
        patchFile: root.tsx.8c182c.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 3dbbb1ee554d96261a2249d8126c8afd11e7ad47
