/**
 * DO NOT EDIT THIS FILE!
 *
 * It is generated each time Hydrogen is built. Instead, override this file by copying it to the
 * `app/routes` directory in your project.
 *
 * @preserve
 */

export async function loader() {
  return new Response(null, {status: 200});
}
