/**
 * DO NOT EDIT THIS FILE!
 *
 * It is generated each time Hydrogen is built. Instead, override this file by copying it to the
 * `app/routes` directory in your project.
 */

import {LoaderArgs, redirect} from '@shopify/hydrogen-remix';

export async function loader({context}: LoaderArgs) {
  const domain = context.storefront.getShopifyDomain();
  return redirect(domain + '/admin');
}
