import * as Types from '@shopify/hydrogen-react/storefront-api-types';

/**
 * This file is automatically generated. Do not modify directly; instead, update the associated query that lives next to this file and run the `codegen` script again.
 **/

export type Media_ExternalVideo_Fragment = {
  __typename: 'ExternalVideo';
  id: string;
  mediaContentType: Types.MediaContentType;
  alt?: string | null;
  previewImage?: {__typename?: 'Image'; url: string} | null;
};

export type Media_MediaImage_Fragment = {
  __typename: 'MediaImage';
  id: string;
  mediaContentType: Types.MediaContentType;
  alt?: string | null;
  image?: {
    __typename?: 'Image';
    url: string;
    width?: number | null;
    height?: number | null;
  } | null;
  previewImage?: {__typename?: 'Image'; url: string} | null;
};

export type Media_Model3d_Fragment = {
  __typename: 'Model3d';
  id: string;
  mediaContentType: Types.MediaContentType;
  alt?: string | null;
  sources: Array<{__typename?: 'Model3dSource'; mimeType: string; url: string}>;
  previewImage?: {__typename?: 'Image'; url: string} | null;
};

export type Media_Video_Fragment = {
  __typename: 'Video';
  id: string;
  mediaContentType: Types.MediaContentType;
  alt?: string | null;
  sources: Array<{__typename?: 'VideoSource'; mimeType: string; url: string}>;
  previewImage?: {__typename?: 'Image'; url: string} | null;
};

export type MediaFragment =
  | Media_ExternalVideo_Fragment
  | Media_MediaImage_Fragment
  | Media_Model3d_Fragment
  | Media_Video_Fragment;

export type CollectionContentFragment = {
  __typename?: 'Collection';
  id: string;
  handle: string;
  title: string;
  descriptionHtml: string;
  heading?: {__typename?: 'Metafield'; value: string} | null;
  byline?: {__typename?: 'Metafield'; value: string} | null;
  cta?: {__typename?: 'Metafield'; value: string} | null;
  spread?: {
    __typename?: 'Metafield';
    reference?:
      | {__typename?: 'Collection'}
      | {__typename?: 'GenericFile'}
      | {
          __typename: 'MediaImage';
          id: string;
          mediaContentType: Types.MediaContentType;
          alt?: string | null;
          image?: {
            __typename?: 'Image';
            url: string;
            width?: number | null;
            height?: number | null;
          } | null;
          previewImage?: {__typename?: 'Image'; url: string} | null;
        }
      | {__typename?: 'Page'}
      | {__typename?: 'Product'}
      | {__typename?: 'ProductVariant'}
      | {
          __typename: 'Video';
          id: string;
          mediaContentType: Types.MediaContentType;
          alt?: string | null;
          sources: Array<{
            __typename?: 'VideoSource';
            mimeType: string;
            url: string;
          }>;
          previewImage?: {__typename?: 'Image'; url: string} | null;
        }
      | null;
  } | null;
  spreadSecondary?: {
    __typename?: 'Metafield';
    reference?:
      | {__typename?: 'Collection'}
      | {__typename?: 'GenericFile'}
      | {
          __typename: 'MediaImage';
          id: string;
          mediaContentType: Types.MediaContentType;
          alt?: string | null;
          image?: {
            __typename?: 'Image';
            url: string;
            width?: number | null;
            height?: number | null;
          } | null;
          previewImage?: {__typename?: 'Image'; url: string} | null;
        }
      | {__typename?: 'Page'}
      | {__typename?: 'Product'}
      | {__typename?: 'ProductVariant'}
      | {
          __typename: 'Video';
          id: string;
          mediaContentType: Types.MediaContentType;
          alt?: string | null;
          sources: Array<{
            __typename?: 'VideoSource';
            mimeType: string;
            url: string;
          }>;
          previewImage?: {__typename?: 'Image'; url: string} | null;
        }
      | null;
  } | null;
};
