# yaml-language-server: $schema=../../recipe.schema.json

title: Subscriptions
image: null
description: |
  This recipe adds subscription capabilities to your Hydrogen storefront by implementing [selling plan groups](https://shopify.dev/docs/api/storefront/latest/objects/SellingPlanGroup) and options. Customers can choose between one-time purchases or recurring subscriptions when available.

  The implementation:
  1. Modifies product detail pages to display subscription options with accurate pricing
  2. Adds a SellingPlanSelector component that presents available subscription options
  3. Enhances GraphQL fragments to fetch all necessary selling plan data
  4. Displays subscription details on applicable cart line items
  With this recipe, merchants can offer flexible purchasing options while maintaining a seamless customer experience.
notes: []
deletedFiles:
  - templates/skeleton/app/components/ProductForm.tsx
ingredients:
  - path: templates/skeleton/app/components/Cart.tsx
    description: null
  - path: templates/skeleton/app/components/SellingPlanSelector.tsx
    description: null
  - path: templates/skeleton/app/styles/selling-plan.css
    description: null
steps:
  - type: INFO
    name: Requirements
    description: >
      This recipe comes pre-configured for our demo storefront using an example
      subscription product with the handle `shopify-wax`.

      #### Setting Up in Your Own Store

      To implement subscriptions in your store:

      1. Install a [Shopify
      Subscriptions](https://apps.shopify.com/shopify-subscriptions) app

      2. Use the app to create selling plans for your products

      3. Assign these selling plans to any products you want to offer as
      subscriptions
  - type: COPY_INGREDIENTS
    name: Copy ingredients
    description: Copy the ingredients from the template directory to the current directory.
    ingredients:
      - templates/skeleton/app/components/Cart.tsx
      - templates/skeleton/app/components/SellingPlanSelector.tsx
      - templates/skeleton/app/styles/selling-plan.css
  - type: PATCH
    name: app/components/CartLineItem.tsx
    description: >
      This step updates the CartLineItem component to show subscription
      information when a customer adds a subscription product to their cart.

      The component now: - Extracts subscription details (sellingPlanAllocation)
      from cart line data - Displays the subscription plan name when available
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.8e657b.patch
  - type: PATCH
    name: app/lib/fragments.ts
    description: >
      # Add Selling Plan Data to Cart Queries

      Updates GraphQL cart fragments to include selling plan information. Adds
      the `sellingPlanAllocation` field with plan names to all cart line
      fragments, enabling the display of subscription details (like "Subscribe
      and save 10%") directly in the cart.
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.e8eb04.patch
  - type: PATCH
    name: app/routes/_index.tsx
    description:
      Removes collection and product components from homepage. Replaces
      with single heading and link to subscription product example
      `/products/shopify-wax`.
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.8041d5.patch
  - type: PATCH
    name: app/routes/products.$handle.tsx
    description:
      Adds SellingPlanSelector component to display subscription options
      on product pages. Handles pricing adjustments, maintains selection state
      via URL parameters, and updates add-to-cart functionality. Fetches
      subscription data through new GraphQL fragments.
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.3e0b7e.patch
commit: 74ef1ba7d41988350e9d2c81731c90381943d1f0
llms:
  userQueries:
    - How do I add subscription options to my Shopify Hydrogen store?
    - What are selling plan groups in Shopify?
    - How do I display subscription pricing on product pages?
    - Can customers choose between one-time purchases and subscriptions?
    - How do I implement recurring delivery options in my Hydrogen store?
    - How do selling plans work with the cart in Hydrogen?
    - How do I show subscription details in the cart?
    - What GraphQL fragments do I need for subscription functionality?
    - How do I handle price adjustments for subscription options?
    - Can I customize the appearance of subscription options?
    - How do I test if my subscription implementation is working correctly?
    - What's the difference between one-time purchase and subscription in
      Shopify?
    - How do I set up selling plan allocations in my Hydrogen store?
    - Can customers modify their subscription options after purchase?
  troubleshooting:
    - issue: Why isn't my subscription option showing up on the product page?
      solution:
        Make sure your product has selling plan groups configured in your
        Shopify admin. The subscription options will only appear if the product
        has at least one selling plan group associated with it.
    - issue: The subscription price isn't calculating correctly
      solution:
        The subscription price calculation depends on the price adjustments
        defined in your selling plans. Check the `SellingPlanPrice` component to
        ensure it's correctly processing all types of price adjustments (fixed
        amount, fixed price, and percentage). Verify that your selling plan
        configuration in Shopify admin has the correct discount values.
    - issue: Subscription information isn't showing in the cart
      solution:
        Check that the `CartLineItem.tsx` file has been properly updated to
        include the selling plan allocation information. Make sure the GraphQL
        fragments in `fragments.ts` include the `sellingPlanAllocation` field to
        fetch the necessary subscription data from the API.
    - issue: I'm getting an error when selecting a subscription option
      solution:
        This could be due to incorrect URL handling for selling plans. Ensure
        that the `selectedSellingPlanId` is being properly extracted from the
        URL and that the `SellingPlanSelector` component is correctly passing
        the selected plan to the cart. Check for any console errors that might
        provide more details about the issue.
    - issue: How do I add more subscription options to my product?
      solution:
        Subscription options are managed in your Shopify admin. Go to Settings
        > Shipping and delivery > Selling plans, and create or modify your
        subscription offerings there. The changes will automatically reflect in
        your storefront once the selling plans are associated with your
        products.
    - issue:
        The 'Subscribe' button is disabled even though I selected a subscription
        option
      solution:
        The 'Subscribe' button is disabled when either the selected variant is
        not available for sale or when no selling plan is selected. Check that
        both a valid variant and a selling plan are selected. Also verify that
        the `disabled` condition in the `AddToCartButton` component is
        evaluating correctly.
    - issue: My one-time purchase option disappeared after implementing subscriptions
      solution: The recipe replaces the standard variant selector with the
        subscription selector when selling plans are available. If you want to
        offer both one-time purchases and subscriptions, you'll need to modify
        the `ProductForm` component to include both options. Consider adding a
        toggle between one-time purchase and subscription modes.
    - issue: The subscription discount isn't showing on the product page
      solution:
        Check that the `SellingPlanPrice` component is correctly rendering the
        discounted price. Make sure your selling plans have price adjustments
        configured in Shopify admin, and that the price calculation logic in the
        component correctly handles all types of adjustments (percentage, fixed
        amount, fixed price).
    - issue: How do I style the subscription options differently?
      solution: The recipe includes a `selling-plan.css` file for styling
        subscription-related components. You can modify this file to customize
        the appearance of subscription options. The main styling classes are
        `.selling-plan-group`, `.selling-plan`, `.selected`, and `.unselected`.
    - issue:
        Customers are confused about subscription options - how can I make them
        clearer?
      solution:
        Consider enhancing the `SellingPlanGroup` component to provide more
        descriptive information about each subscription option. You could add
        tooltips explaining the benefits of each plan, show the calculated
        savings more prominently, or add more descriptive labels. You might also
        want to add a FAQ section specifically about subscriptions.
