# yaml-language-server: $schema=../../recipe.schema.json

title: Subscriptions
image: null
description: |
  This recipe adds subscription capabilities to your Hydrogen storefront by implementing [selling plan groups](https://shopify.dev/docs/api/storefront/latest/objects/SellingPlanGroup) and options. Customers can choose between one-time purchases or recurring subscriptions when available.

  The implementation:
  1. Modifies product detail pages to display subscription options with accurate pricing
  2. Adds a SellingPlanSelector component that presents available subscription options
  3. Enhances GraphQL fragments to fetch all necessary selling plan data
  4. Displays subscription details on applicable cart line items
  With this recipe, merchants can offer flexible purchasing options while maintaining a seamless customer experience.
notes: []
deletedFiles:
  - templates/skeleton/app/components/ProductForm.tsx
ingredients:
  - path: templates/skeleton/app/components/Cart.tsx
    description: Cart component to show subscription options
  - path: templates/skeleton/app/components/SellingPlanSelector.tsx
    description: A component that simplifies selecting sellingPlans subscription options
  - path: templates/skeleton/app/styles/selling-plan.css
    description: CSS file for selling plan styles in the product page
steps:
  - type: INFO
    name: Requirements
    description: >
      This recipe comes pre-configured for our demo storefront using an example
      subscription product with the handle `shopify-wax`.

      #### Setting Up in Your Own Store

      To implement subscriptions in your store:

      1. Install a [Shopify
      Subscriptions](https://apps.shopify.com/shopify-subscriptions) app

      2. Use the app to create selling plans for your products

      3. Assign these selling plans to any products you want to offer as
      subscriptions
  - type: COPY_INGREDIENTS
    name: Copy ingredients
    description: Copy the ingredients from the template directory to the current directory.
    ingredients:
      - templates/skeleton/app/components/Cart.tsx
      - templates/skeleton/app/components/SellingPlanSelector.tsx
      - templates/skeleton/app/styles/selling-plan.css
  - type: PATCH
    name: Render the selling plan in the cart
    description: >
      CartLineItem now displays subscription plan names when customers add
      subscription products to their cart.
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.8e657b.patch
  - type: PATCH
    name: Add Selling Plan Data to Cart Queries
    description: >
      Updates cart GraphQL fragments to include subscription plan names,
      enabling e.g "Subscribe and save" messaging in the applicable cart lines
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.e8eb04.patch
  - type: PATCH
    name: Update the home page
    description: >
      Replaces the base home page with single heading and link to a
      demonstration subscription product at `/products/shopify-wax`.
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.8041d5.patch
  - type: PATCH
    name: Add SellingPlanSelector to product pages
    description: >
      Adds SellingPlanSelector component to display subscription options on
      product pages. Handles pricing adjustments, maintains selection state via
      URL parameters, and updates add-to-cart functionality. Fetches
      subscription data through the updated cart GraphQL fragments.
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.3e0b7e.patch
commit: b3fc64a2c9b91cecf993d34b3286a6af85729365
