# yaml-language-server: $schema=../../recipe.schema.json

title: Subscriptions
summary: Add subscription-based products to your Hydrogen storefront.
description: |
  This recipe lets you sell subscription-based products on your Hydrogen storefront by implementing [selling plan groups](https://shopify.dev/docs/api/storefront/latest/objects/SellingPlanGroup). Your customers will be able to choose between one-time purchases or recurring subscriptions for any products with available selling plans.


  In this recipe you'll make the following changes:


  1. Set up a subscriptions app in your Shopify admin and add selling plans to any products that will be sold as subscriptions.
  2. Modify product detail pages to display subscription options with accurate pricing using the `SellingPlanSelector` component.
  3. Enhance GraphQL fragments to fetch all necessary selling plan data.
  4. Display subscription details on applicable line items in the cart.
  5. Add a **Subscriptions** page where customers can manage their subscriptions, which includes the option to cancel active subscriptions.
notes: []
requirements: >
  To implement subscriptions in your own store, you need to install a
  subscriptions app in your Shopify admin. In this recipe, we'll use the
  [Shopify Subscriptions app](https://apps.shopify.com/shopify-subscriptions).
ingredients:
  - path: templates/skeleton/app/components/SellingPlanSelector.tsx
    description: Displays the available subscription options on product pages.
  - path: templates/skeleton/app/graphql/customer-account/CustomerSubscriptionsMutations.ts
    description: Mutations for managing customer subscriptions.
  - path: templates/skeleton/app/graphql/customer-account/CustomerSubscriptionsQuery.ts
    description: Queries for managing customer subscriptions.
  - path: templates/skeleton/app/routes/account.subscriptions.tsx
    description: Subscriptions management page.
  - path: templates/skeleton/app/styles/account-subscriptions.css
    description: Subscriptions management page styles.
  - path: templates/skeleton/app/styles/selling-plan.css
    description: Styles the `SellingPlanSelector` component.
deletedFiles: []
steps:
  - type: INFO
    index: 1
    name: Set up the Shopify Subscriptions app
    description: >
      1. Install the [Shopify Subscriptions
      app](https://apps.shopify.com/shopify-subscriptions).

      2. In your Shopify admin, [use the Subscriptions
      app](https://admin.shopify.com/apps/subscriptions-remix/app) to create one
      or more subscription plans.

      3. On the [Products](https://admin.shopify.com/products) page, open any
      products that will be sold as subscriptions and add the relevant
      subscription plans in the **Purchase options** section.

      The Hydrogen demo storefront comes pre-configured with an example
      subscription product with the handle `shopify-wax`.
  - type: COPY_INGREDIENTS
    index: 2
    name: Add ingredients to your project
    description: Copy all the files found in the `ingredients/` directory into your project.
    ingredients:
      - templates/skeleton/app/components/SellingPlanSelector.tsx
      - templates/skeleton/app/graphql/customer-account/CustomerSubscriptionsMutations.ts
      - templates/skeleton/app/graphql/customer-account/CustomerSubscriptionsQuery.ts
      - templates/skeleton/app/routes/account.subscriptions.tsx
      - templates/skeleton/app/styles/account-subscriptions.css
      - templates/skeleton/app/styles/selling-plan.css
  - type: PATCH
    index: 3
    name: Render the selling plan in the cart
    description: >
      1. Update `CartLineItem` to show subscription details when they're
      available.

      2. Extract `sellingPlanAllocation` from cart line data, display the plan
      name, and standardize component import paths.
    diffs:
      - file: app/components/CartLineItem.tsx
        patchFile: CartLineItem.tsx.8e657b.patch
  - type: PATCH
    index: 4
    name: Update ProductForm to support subscriptions
    description: >
      1. Add conditional rendering to display either subscription options or
      standard variant selectors.

      2. Implement `SellingPlanSelector` and `SellingPlanGroup` components to
      handle subscription plan selection.

      3. Update `AddToCartButton` to include selling plan data when
      subscriptions are selected.
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.8e409a.patch
  - type: PATCH
    index: 5
    name: Update ProductPrice to display subscription pricing
    description: >
      1. Add a `SellingPlanPrice` function to calculate adjusted prices based on
      subscription plan type (fixed amount, fixed price, or percentage).

      2. Add logic to handle different price adjustment types and render the
      appropriate subscription price when a selling plan is selected.
    diffs:
      - file: app/components/ProductPrice.tsx
        patchFile: ProductPrice.tsx.a5e47f.patch
  - type: PATCH
    index: 6
    name: Add selling plan data to cart queries
    description: >
      Add a `sellingPlanAllocation` field with the plan name to the standard and
      componentizable cart line GraphQL fragments. This displays subscription
      details in the cart.
    diffs:
      - file: app/lib/fragments.ts
        patchFile: fragments.ts.e8eb04.patch
  - type: PATCH
    index: 7
    name: Add SellingPlanSelector to product pages
    description: >
      1. Add the `SellingPlanSelector` component to display subscription options
      on product pages.

      2. Add logic to handle pricing adjustments, maintain selection state using
      URL parameters, and update the add-to-cart functionality.

      3. Fetch subscription data through the updated cart GraphQL fragments.
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.3e0b7e.patch
  - type: PATCH
    index: 8
    name: Add a link to the Subscriptions page
    description: |
      Add a `Subscriptions` link to the account menu.
    diffs:
      - file: app/routes/account.tsx
        patchFile: account.tsx.a0203d.patch
llms:
  userQueries:
    - How do I add subscriptions to my Hydrogen storefront?
    - How do I add selling plans to my Hydrogen storefront?
    - How do I display subscription details on applicable line items in the cart?
  troubleshooting:
    - issue: I'm getting an error when I try to add a subscription to my storefront.
      solution: Make sure you've installed the Shopify Subscriptions app and set up
        selling plans for subscription products in your Shopify admin.
    - issue: I'm not seeing the subscription options on my product pages.
      solution: Make sure you've installed the Shopify Subscriptions app and set up
        selling plans for subscription products in your Shopify admin.
    - issue: I'm not seeing the subscription details on my cart line items.
      solution: Make sure you've installed the Shopify Subscriptions app and set up
        selling plans for subscription products in your Shopify admin.
commit: 2ff53492d0c9152bd59063ae6ea34576ea9a4608
