/**
 * Generates src/graphql/generated/iso-codes.ts: runtime mirrors of the
 * ShopifyCountryCode/ShopifyLanguageCode types (the intersection of the Storefront and
 * Customer Account API enums). Runs as part of `pnpm codegen`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const GENERATED_DIR = resolve(import.meta.dirname, "../src/graphql/generated");
const OUTPUT_PATH = resolve(GENERATED_DIR, "iso-codes.ts");

const countryCodes = schemaEnumIntersection("CountryCode");
const languageCodes = schemaEnumIntersection("LanguageCode");

writeFileSync(
  OUTPUT_PATH,
  `/**
 * Generated by scripts/generate-iso-codes.ts — do not edit. Regenerate with \`pnpm codegen\`.
 *
 * Runtime mirrors of the ShopifyCountryCode/ShopifyLanguageCode types: the intersection of
 * the Storefront and Customer Account API enums, for validating locale codes at runtime
 * boundaries (URL prefixes, form input, session data).
 */
import type {
  CountryCode as CustomerAccountCountryCode,
  LanguageCode as CustomerAccountLanguageCode,
} from "./customer-account-api-types";
import type {
  CountryCode as StorefrontCountryCode,
  LanguageCode as StorefrontLanguageCode,
} from "./storefront-api-types";

export const SHOPIFY_COUNTRY_CODES = ${toArrayLiteral(countryCodes)} as const satisfies readonly Extract<
  StorefrontCountryCode,
  CustomerAccountCountryCode
>[];

export const SHOPIFY_LANGUAGE_CODES = ${toArrayLiteral(languageCodes)} as const satisfies readonly Extract<
  StorefrontLanguageCode,
  CustomerAccountLanguageCode
>[];
`,
);

console.log(
  `Generated ${OUTPUT_PATH} (${countryCodes.length} countries, ${languageCodes.length} languages)`,
);

function schemaEnumIntersection(enumName: string): string[] {
  const storefrontValues = readSchemaEnumValues("storefront.schema.json", enumName);
  const customerAccountValues = new Set(
    readSchemaEnumValues("customer-account.schema.json", enumName),
  );
  return storefrontValues.filter((value) => customerAccountValues.has(value)).toSorted();
}

type IntrospectionEnumType = {
  kind: string;
  name: string;
  enumValues?: Array<{ name: string }>;
};

type IntrospectionSchema = {
  __schema: { types: IntrospectionEnumType[] };
};

function readSchemaEnumValues(schemaFileName: string, enumName: string): string[] {
  const schema: IntrospectionSchema = JSON.parse(
    readFileSync(resolve(GENERATED_DIR, schemaFileName), "utf8"),
  );

  const enumType = schema.__schema.types.find(
    (type) => type.kind === "ENUM" && type.name === enumName,
  );
  if (!enumType?.enumValues?.length) {
    throw new Error(`Enum ${enumName} not found in ${schemaFileName}`);
  }
  return enumType.enumValues.map((value) => value.name);
}

function toArrayLiteral(values: string[]): string {
  return `[\n  ${values.map((value) => JSON.stringify(value)).join(",\n  ")},\n]`;
}
