name: mini-oxygen

up:
  - node:
      version: v16.14.0
      yarn: 1.22.5
  - git_hooks:
      pre-push: script/pre-push.sh

commands:
  bump-version-major:
    run: yarn version --new-version major && git push --follow-tags
    desc: bump the version number (major)
  bump-version-minor:
    run: yarn version --new-version minor && git push --follow-tags
    desc: bump the version number (minor)
  bump-version-patch:
    run: yarn version --new-version patch && git push --follow-tags
    desc: bump the version number (patch)
