# yaml-language-server: $schema=../../recipe.schema.json

gid: cdd523a1-fcd9-4122-aacd-fdd2f2c050e7
title: Infinite scroll for collections
summary: Add infinite scroll pagination to collection pages for seamless product
  browsing
description: |
  This recipe implements infinite scroll functionality on collection pages using the Intersection Observer API.

  Key features:
  - Automatic loading when "Load more" button comes into view using Intersection Observer API
  - Preserves browser history and URL state (replace mode to avoid clutter)
  - Maintains scroll position during navigation
  - Optimized loading with eager/lazy image loading (first 8 products eager, rest lazy)
notes: []
requirements: |
  - Basic understanding of React hooks (useEffect, custom hooks)
  - Familiarity with Shopify's Pagination component
  - Knowledge of intersection observer API concepts
ingredients: []
deletedFiles: []
steps:
  - type: PATCH
    step: "1"
    name: Document infinite scroll in the README
    description: Update the README file with infinite scroll documentation and
      implementation details.
    diffs:
      - file: README.md
        patchFile: README.md.db10ed.patch
  - type: PATCH
    step: "2"
    name: Add infinite scroll to collections
    description: Implement automatic loading with Intersection Observer when users
      scroll to the bottom.
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.f062a9.patch
  - type: PATCH
    step: "3"
    name: Install Intersection Observer library
    description: Add the react-intersection-observer package for viewport detection.
    diffs:
      - file: package.json
        patchFile: package.json.f30b0a.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 0511444a026f5b80c3927fbc2e31b1ab827cfeae
