# yaml-language-server: $schema=../../recipe.schema.json

gid: cdd523a1-fcd9-4122-aacd-fdd2f2c050e7
title: Infinite Scroll for Collections
summary: Add infinite scroll pagination to collection pages for seamless product
  browsing
description: |
  Implements infinite scroll functionality on collection pages using intersection observer.
  Products automatically load as users scroll down, replacing traditional pagination buttons
  with a smooth, continuous browsing experience.

  Key features:
  - Automatic loading when "Load more" button comes into view
  - Preserves browser history and URL state
  - Maintains scroll position during navigation
  - Optimized loading with eager/lazy image loading
notes:
  - The intersection observer triggers when the "Load more" button enters the
    viewport
  - Navigation updates use replace mode to avoid cluttering browser history
  - First 8 products load eagerly for faster initial render
  - Subsequent products use lazy loading to optimize performance
requirements: |
  - Basic understanding of React hooks (useEffect, custom hooks)
  - Familiarity with Shopify's Pagination component
  - Knowledge of intersection observer API concepts
ingredients: []
deletedFiles: []
steps:
  - type: PATCH
    step: "1"
    name: README.md
    description: Updates README with infinite scroll documentation and implementation details
    diffs:
      - file: README.md
        patchFile: README.md.47d06f.patch
  - type: PATCH
    step: "1"
    name: app/routes/collections.$handle.tsx
    description: null
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.903c17.patch
  - type: PATCH
    step: "2"
    name: package.json
    description: null
    diffs:
      - file: package.json
        patchFile: package.json.cfee98.patch
nextSteps: null
llms:
  userQueries: []
  troubleshooting: []
commit: 6681f92e84d42b5a6aca153fb49e31dcd8af84f6
