# yaml-language-server: $schema=../../recipe.schema.json

gid: 6bfa1a39-3a16-4351-b34a-2369c495d5a2
title: Combined Listings
summary: Handle combined listings on product pages and in search results.
description: |
  This recipe lets you more precisely display and manage [combined listings](https://help.shopify.com/en/manual/products/combined-listings-app) on product pages and in search results for your Hydrogen storefront. A combined listing groups separate products together into a single product listing using a shared option like color or size.
  Each product appears as a variant but can have its own title, description, URL, and images.
  In this recipe, you'll make the following changes:

  1. Set up the Combined Listings app in your Shopify admin and group relevant products together as combined listings.
  2. Configure how combined listings will be handled on your storefront.
  3. Update the `ProductForm` component to hide the **Add to cart** button for the parent products of combined listings.
  4. Update the `ProductImage` component to support images from product variants and the product itself.
  5. Show a range of prices for combined listings in `ProductItem`.
notes:
  - This recipe is compatible with React Router 7.9.x and uses consolidated
    imports from 'react-router' instead of separate '@shopify/remix-oxygen' and
    '@remix-run/react' packages.
requirements: |
  - Your store must be on either a [Shopify Plus](https://www.shopify.com/plus) or enterprise plan.
  - Your store must have the [Combined Listings app](https://admin.shopify.com/apps/combined-listings) installed.
ingredients:
  - path: templates/skeleton/app/lib/combined-listings.ts
    description:
      The `combined-listings.ts` file contains utilities and settings for
      handling combined listings.
deletedFiles: []
steps:
  - type: INFO
    step: 1
    name: Set up the Combined Listings app
    description: |
      1. Install the [Combined Listings app](https://admin.shopify.com/apps/combined-listings).

      2. [Create combined listing products in your store](https://help.shopify.com/en/manual/products/combined-listings-app#creating-a-combined-listing).

      3. Add tags to the parent products of combined listings to indicate that they're part of a combined listing (for example `combined`).
  - type: INFO
    step: 2
    name: Configure combined listings behavior
    description: |
      You can customize how the parent products of combined listings are retrieved and displayed.

      To make this process easier, we included a configuration object in the `combined-listings.ts` file that you can edit to customize according to your preferences.

      ```ts
      // Edit these values to customize the combined listings behaviors
      export const combinedListingsSettings = {
        // If true, loading the product page will redirect to the first variant
        redirectToFirstVariant: false,
        // The tag that indicates a combined listing
        combinedListingTag: 'combined',
        // If true, combined listings will not be shown in the product list
        hideCombinedListingsFromProductList: true,
      };
      ```
  - type: NEW_FILE
    step: 3
    name: Add combined listings utilities
    description:
      Create a new `combined-listings.ts` file that contains utilities
      and settings for handling combined listings.
    ingredients:
      - path: templates/skeleton/app/lib/combined-listings.ts
  - type: PATCH
    step: 4
    name: Update the ProductForm component
    description: |
      1. Update the `ProductForm` component to hide the **Add to cart** button for the parent products of combined listings and for variants' selected state.
      2. Update the `Link` component to not replace the current URL when the product is a combined listing parent product.
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.649d3b.patch
  - type: PATCH
    step: 5
    name: Extend the ProductImage component
    description: |
      Update the `ProductImage` component to support images from both product variants and the product itself.
    diffs:
      - file: app/components/ProductImage.tsx
        patchFile: ProductImage.tsx.42c3b6.patch
  - type: PATCH
    step: 6
    name: Show a range of prices for combined listings in ProductItem
    description: |
      Update `ProductItem.tsx` to show a range of prices for the combined listing parent product instead of the variant price.
    diffs:
      - file: app/components/ProductItem.tsx
        patchFile: ProductItem.tsx.d3223b.patch
  - type: PATCH
    step: 7
    name: (Optional) Add redirect utility to first variant of a combined listing
    description: |
      If you want to redirect automatically to the first variant of a combined listing when the parent handle is selected, add a redirect utility that's called whenever the parent handle is requested.
    diffs:
      - file: app/lib/redirect.ts
        patchFile: redirect.ts.6d9851.patch
  - type: PATCH
    step: 8
    name: app/routes/collections.all.tsx
    description: null
    diffs:
      - file: app/routes/collections.all.tsx
        patchFile: collections.all.tsx.38a40d.patch
  - type: PATCH
    step: 9
    name: Update queries for combined listings
    description: |
      1. Add the `tags` property to the items returned by the product query.
      2. (Optional) Add the filtering query to the product query to exclude combined listings.
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.243e26.patch
  - type: PATCH
    step: 10
    name: (Optional) Filter out combined listings from collections pages
    description: |
      Since it's not possible to directly apply query filters when retrieving collection products, you can manually filter out combined listings after they're retrieved based on their tags.
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.f062a9.patch
  - type: PATCH
    step: 11
    name: Update the product page
    description: |
      1. Display a range of prices for combined listings instead of the variant price.
      2. Show the featured image of the combined listing parent product instead of the variant image.
      3. (Optional) Redirect to the first variant of a combined listing when the handle is requested.
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.6f2e82.patch
  - type: PATCH
    step: 12
    name: Update stylesheet
    description: |
      Add a class to the product item to show a range of prices for combined listings.
    diffs:
      - file: app/styles/app.css
        patchFile: app.css.881a99.patch
nextSteps: |
  - Test your implementation by going to your store and searching for a combined listing. Make sure that the combined listing's details appear in the search results and on the product page.
  - (Optional) [Place a test order](https://help.shopify.com/en/manual/checkout-settings/test-orders) to see how orders for combined listings appear in your Shopify admin.
llms:
  userQueries:
    - How can I show combined listings on product pages and search results using
      Hydrogen?
    - How can I display the featured image of the combined listing parent
      product instead of the variant image?
    - How can I redirect to the first variant of a combined listing when the
      handle is requested?
    - How can I filter out combined listings from the product list when using
      Shopify headless?
    - How can I show the price range for combined listings instead of the
      variant price?
  troubleshooting:
    - issue: Combined listings are being displayed in the product list.
      solution:
        Make sure to tag combined listing parent products in the Shopify admin
        and use that tag to filter out combined listings from the product list
        in the GraphQL query.
commit: aef8cf795ea8f68077d6fa1f1649e2791f6658a7
