# yaml-language-server: $schema=../../recipe.schema.json

title: Combined Listings
summary: Handle Shopify combined listings in product pages and search results.
description: >
  
  This recipe handles Shopify [combined
  listings](https://help.shopify.com/en/manual/products/combined-listings-app)
  in product pages and search results.
notes:
  - Combined listings are available only to stores on a [Shopify
    Plus](https://www.shopify.com/plus) or enterprise plan.
requirements: |
  - Install the [Combined Listings app](https://admin.shopify.com/apps/combined-listings) in your store.
  - [Create combined listing products in your store](https://help.shopify.com/en/manual/products/combined-listings-app#creating-a-combined-listing).
  - Add a tag to any combined listing parent products to indicate they're a combined listing, for example `combined`.
ingredients:
  - path: templates/skeleton/app/lib/combined-listings.ts
    description: Utilities and settings for handling combined listings.
deletedFiles: []
steps:
  - type: INFO
    name: Configure combined listings behavior
    description: >
      Combined listings work out of the box, but you can customize specific
      behaviors when retrieving and displaying combined listing parent products.


      To make this process easier, we included a configuration object in the
      `combined-listings.ts` file that you can edit to customize according to
      your preferences.


      ```ts

      // Edit these values to customize the combined listings behaviors

      export const combinedListingsSettings = {
        // If true, loading the product page will redirect to the first variant
        redirectToFirstVariant: false,
        // The tag that indicates a combined listing
        combinedListingTag: 'combined',
        // If true, combined listings will not be shown in the product list
        hideCombinedListingsFromProductList: true,
      };

      ```
  - type: COPY_INGREDIENTS
    name: Add ingredients to your project
    description: Copy all the files found in the `ingredients/` directory to the
      current directory.
    ingredients:
      - templates/skeleton/app/lib/combined-listings.ts
  - type: PATCH
    name: Update the `ProductForm` component
    description: >
      Update the `ProductForm` component to hide the `Add to cart` button for
      combined listings parent products, as well as the selected state for
      variants.
    diffs:
      - file: app/components/ProductForm.tsx
        patchFile: ProductForm.tsx.8e409a.patch
  - type: PATCH
    name: Extend the `ProductImage` component
    description: >
      Update the `ProductImage` component to support images from both product
      variants and the product itself.
    diffs:
      - file: app/components/ProductImage.tsx
        patchFile: ProductImage.tsx.4e6c4c.patch
  - type: PATCH
    name: Show a range of prices for combined listings in `ProductItem`
    description: |
      If the product is a combined listing, show a range of prices for the
      combined listing parent product instead of the variant price.
    diffs:
      - file: app/components/ProductItem.tsx
        patchFile: ProductItem.tsx.8ddc67.patch
  - type: PATCH
    name: (optional) Add combined listings redirect utility
    description: >
      If you wish to redirect automatically to the first variant of a combined
      listing when the parent handle is selected, add a utility to redirect to
      the first variant of a combined listing when the handle of the parent is
      requested, add a utility to redirect to the first variant of a combined
      listing.
    diffs:
      - file: app/lib/redirect.ts
        patchFile: redirect.ts.1e6242.patch
  - type: PATCH
    name: Update queries for combined listings
    description: >
      - Add the `tags` property to the ones returned by the product query.

      - (optional) Add the filtering query to the product query to exclude
      combined listings.
    diffs:
      - file: app/routes/_index.tsx
        patchFile: _index.tsx.8041d5.patch
  - type: PATCH
    name: (optional) Filter out combined listings from individual collections pages
    description: >
      Since it's not possible to directly apply query filters when retrieving
      collection products, you can manually filter out combined listings after
      they are retrieved, based on their tags.
    diffs:
      - file: app/routes/collections.$handle.tsx
        patchFile: collections.$handle.tsx.951367.patch
  - type: PATCH
    name: (optional) Filter out combined listings from collections index page
    description: >
      Update the `collections.all` route to filter out combined listings from
      the search results, and include the price range for combined listings.
    diffs:
      - file: app/routes/collections.all.tsx
        patchFile: collections.all.tsx.75880b.patch
  - type: PATCH
    name: Update the product page
    description: >
      - Display a range of prices for combined listings instead of the variant
      price.

      - Show the featured image of the combined listing parent product instead
      of the variant image.

      - (optional) Redirect to the first variant of a combined listing when the
      handle is requested
    diffs:
      - file: app/routes/products.$handle.tsx
        patchFile: products.$handle.tsx.3e0b7e.patch
  - type: PATCH
    name: Update stylesheet
    description: >
      Add a class to the product item to show a range of prices for combined
      listings.
    diffs:
      - file: app/styles/app.css
        patchFile: app.css.e88d35.patch
llms:
  userQueries:
    - How can I show combined listings in product pages and search results using
      Hydrogen?
    - How can I display the featured image of the combined listing parent
      product instead of the variant image?
    - How can I redirect to the first variant of a combined listing when the
      handle is requested?
    - How can I filter out combined listings from the product list when using
      Shopify headless?
    - How can I show the price range for combined listings instead of the
      variant price?
  troubleshooting:
    - issue: Combined listings are being displayed in the product list.
      solution: Make sure to tag combined listing parent products in the Shopify Admin
        and use that tag to filter out combined listings from the product list
        in the GraphQL query.
commit: 62dc2f367bc73d4f402b96213de9e2f933d0441c
