/*
 * This component is autogenerated. Do not modify it manually.
 */

import {ImageText} from './ImageText';
import type {ImageTextFragment} from 'storefrontapi.generated';

export type SectionTypes = ImageTextFragment;
export type RouteSections = Array<SectionTypes>;

export function Sections({sections}: {sections: Array<SectionTypes>}) {
  return (
    <>
      {sections.map((section) => {
        switch (section.type) {
          case 'section_image_text':
            return <ImageText {...section} key={section.id} />;
          default:
            return null;
        }
      })}
    </>
  );
}
