/**
 * DO NOT EDIT THIS FILE!
 *
 * It is generated each time Hydrogen is built. Instead, override this file by copying it to the
 * `app/routes` directory in your project.
 *
 * @preserve
 */

import {redirect, type LoaderArgs} from '@remix-run/server-runtime';

export async function loader({context}: LoaderArgs) {
  const domain = context.storefront.getShopifyDomain();
  return redirect(domain + '/admin');
}
